#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "omniDrive.h"

#define STARTING_ANGLE 90

OmniMotors motors;
task main() {
    waitForStart();

    motors.frontLeft  = frontLeft;
    motors.frontRight = frontRight;
    motors.backLeft   = backLeft;
    motors.backRight  = backRight;
    omniDrivePolar(motors,50,STARTING_ANGLE);
    wait1Msec(4000);
    omniDrivePolar(motors,0,STARTING_ANGLE);

    int accumulatedTime = 0, time;
    while(true){

        time = random[3000 - accumulatedTime] - accumulatedTime;

        omniDrivePolar(motors,sgn(time)*75,180);
        accumulatedTime += time;

        wait1Msec(abs(time));
        omniDrivePolar(motors,0,0);
}
}
