#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "omniDrive.H"
#include "C:\Users\Tim\Desktop\rdpartyrobotcdr-3.1\drivers\hitechnic-irseeker-v2.h"
int irs[5];

OmniMotors motors;
task main()
{
    motors.frontLeft  = frontLeft;
    motors.frontRight = frontRight;
    motors.backLeft   = backLeft;
    motors.backRight  = backRight;
    HTIRS2readAllACStrength(IRSensor, irs[0], irs[1], irs[2], irs[3], irs[4]);
    omniDrivePolarWithSpin(motors, 50, 90, ((irs[0] + irs[1])/2 - (irs[2] + irs[3] + irs[4])/3));


}
