#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#pragma platform(Tetrix)

/* Motor Roles:
 * - ExampleMotor: Does things
 * - MotorA: moves ramp
 * - MotorE: moves robot, front left wheel
 * - MotorD: moves robot, back right wheel
 * - MotorF: moves robot, front right wheel
 * - MotorG: moves robot, back left wheel
 * - MotorH: moves arm up and down
 * - servo1: moves hand
 * TODO: add more of this
 */

//#define ENABLE_LATCH
#define ENABLE_ARM
//#define ENABLE_CLAW
//#define ENABLE_MACRO_BUTTONS

void omniDrive(int joyx, int joyy, float scale, int joyspin);
#ifdef ENABLE_LATCH
void latchrelease();
#endif
#ifdef ENABLE_ARM
void armMove(int moveUp);
#endif
#ifdef ENABLE_MACRO_BUTTONS
//Refine presets
void armMacro (int set, int sensor);
const int presets[4] = {0, 360,  720, 1080};
#endif
#define NORMAL_SCALE 1.0
#define SLOW_SCALE 0.5
float scale = NORMAL_SCALE;
task main() {
    while(true) {
        getJoystickSettings(joystick);

#ifdef ENABLE_LATCH

        if(joy1Btn(10)) {
            //Release Latch
            latchrelease();
        }

#endif
//see if btn 8 is depressed, if so sets a scale factor for all movement calculations in omnidrive function
        if(joy1Btn(8)) {
            scale = SLOW_SCALE;
        } else {
            scale = NORMAL_SCALE;
        }
        omniDrive(joystick.joy1_x1, joystick.joy1_y1, scale, joystick.joy1_x2);
      /*  if(joy1Btn(5)) {
            motor[motorH] = 50;
        }
        if (joy1Btn(7)) {
            motor[motorH]=-50;
        }*/

#ifdef ENABLE_CLAW

        switch(joystick.joy1_TopHat) {
        case 0:
        case 1:
        case 7:
            servo[servo1] = 40;
            break;

        case 5:
        case 4:
        case 3:
            servo[servo1] = -40;
            break;

        default:
            servo[servo1] = 0;
        }

#endif

        int preset;

#ifdef ENABLE_MACRO_BUTTONS
        if(joy1Btn(1)) {
            preset = 1;
        }
        if(joy1Btn(2)) {
            preset = 2;
        }
        if(joy1Btn(3)) {
            preset = 3;
        }
        if(joy1Btn(4)) {
            preset = 4;
        }
#endif

#ifdef ENABLE_ARM

        if(joy1Btn(7) && joy1Btn(5)) {
            //if both 7 and 5 are depressed DO NOTHING!
            writeDebugStreamLine("Both #5 and #7 depressed");
            preset = -1;
            armMove(0);
        } else if(joy1Btn(7)) {
		//Call are movement function; move down
            armMove(-1);
            preset = -1;
            writeDebugStreamLine("joy1_btn 7 depressed; armMove false initiated");
        } else if(joy1Btn(5)) {
            //call arm movement function; Move up
            armMove(1);
            preset = -1;
            writeDebugStreamLine("joy1_btn 5 depressed; armMove true initiated");
	}
	else {
	    armMove(0);
	}

#endif

#ifdef ENABLE_MACRO_BUTTONS
        int encoder;
        encoder += nMotorEncoder[motorH];
        nMotorEncoder[motorH] = 0;
        if(preset >= 0) {
            armMacro(presets[preset], encoder);
        } else {

        }

#endif

    }
}


//float scale: multiplies by the scale factor to receive new speed
void omniDrive(int joyx, int joyy, float scale, int joyspin) {
    float x    = (100.0/128) * (float)joyx,
          y    = (100.0/128) * (float)joyy,
          spin = (50.0/128)  * (float)joyspin;

    int upRightSpeed = (x + y)  / sqrt(2);
    int upLeftSpeed  = (-x + y) / sqrt(2);
		int topRight, topLeft, bottomRight, bottomLeft;
		topRight = (upLeftSpeed  - spin) * scale;
		topLeft = (upRightSpeed + spin) * scale;
		bottomRight = (upRightSpeed - spin) * scale;
		bottomLeft = (upLeftSpeed  + spin) * scale;
    motor[motorE] = topLeft;
    motor[motorD] = bottomRight;
    motor[motorG] = bottomLeft;
    motor[motorF] = topRight;
    writeDebugStreamLine("motorF:%d,motorE:%d,motorD:%d,motorG:%d", topRight,topLeft,bottomRight,bottomLeft);
}

#ifdef ENABLE_LATCH

void latchrelease() {
    //TODO: write latch release
    writeDebugStreamLine("Latch Release initiated");
}

#endif

#ifdef ENABLE_ARM

void armMove(int moveUp) {
    //TODO: Tune movement speed
    #define ARM_SPEED 40
    //TODO: Motor designation changed
    if(moveUp>0) {
        motor[motorH] = ARM_SPEED;
    } else if(moveUp<0){
        motor[motorH] = - ARM_SPEED;
    }
    else{
        motor[motorH] = 0;
    }
}

#endif

#ifdef ENABLE_MACRO_BUTTONS

void armMacro (int set, int sensor){
#define KP 1
#define MIN_ERR 15
    int err = set - sensor;
    if(abs(err) <= MIN_ERR){
        motor[motorH] = KP * err;
    } else {
        motor[motorH] = 0;
    }
}

#endif
