#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     rampMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    sensorServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    clawServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "omniDrive.h"

#define Joint_Distance 3 //need to take measurement of distance from pole to edge of joint
#define Arm_Distance 13 //Distance from pole arm needs to be to unfold into ring placing position

bool sensorCheck();
void placeRing();

OmniMotors motors;

int distance_in_cm = 0;

task main(){
 motors.frontLeft  = frontLeft;
 motors.frontRight = frontRight;
 motors.backLeft   = backLeft;
 motors.backRight  = backRight;
 while(sensorCheck()){
  omniDrivePolar(motors,100,0);
  wait1Msec(1000);//need to check move speed, make sure it moves to correct spot
  omniDrivePolar(motors,0,0);
  sensorCheck();
 }//while
 placeRing();
}//main

bool sensorCheck(){
 int servoAccumulator = 0;
 distance_in_cm = 0;
 while(distance_in_cm == 0){
  if (SensorValue[sonarSensor] < 255){
   distance_in_cm = SensorValue[sonarSensor];
  }else{
   omniDrivePolar(motors,100,90);
   wait1Msec(1000);//need to check this gets right up against board, need to move a bit if problems occur
   omniDrivePolar(motors,0,90);
  }//else
 }//while
 while(SensorValue[sonarSensor] == distance_in_cm){
  servo[sensorServo] = servoAccumulator; //need to add this servo, may be forced to use arm instead
  servoAccumulator += 0.5;
 }//while

 if(SensorValue[sonarSensor] == (distance_in_cm - Joint_Distance) || SensorValue[sonarSensor] > (distance_in_cm + 10)) {
  return false;
 }else{
  return true;
 }
}

void placeRing(){
 omniDrivePolar(motors,40,90);
 wait1Msec(1500);
 omniDrivePolar(motors,0,90);
 while(SensorValue[sonarSensor] > distance_in_cm - Arm_Distance){
  omniDrivePolar(motors,50,285);
 }//while
 motor[armMotor] = 50; //need to test and edit, maybe come up with another way to make the arm go where we want
 wait1Msec(1000); //again, needs testing
 motor[armMotor] = 0;
 servo[clawServo] = 150;
 omniDrivePolar(motors,40,90);
 wait1Msec(200);
 motor[armMotor] = 10;
 omniDrivePolar(motors,20,90);
 servo[clawServo] = 160;
 wait1Msec(200);
 servo[clawServo] = 170;
 wait1Msec(200);
 servo[clawServo] = 180;
 wait1Msec(200);
 omniDrivePolar(motors,0,90);
 motor[armMotor] = 20;
 wait1Msec(300);
 motor[armMotor] = 0;
 omniDrivePolar(motors,50,270);
 wait1Msec(3000);
 omniDrivePolar(motors,0,0);
}
