#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


/* Motor Roles:
 * - MotorA           moves ramp
 * - frontLeftMotor   moves robot, front left wheel
 * - backRightMotor   moves robot, back right wheel
 * - frontRightMotor  moves robot, front right wheel
 * - backLeftMotor    moves robot, back left wheel
 * - motorA           moves arm up and down
 * - clawServo        moves hand
 */

//#define ENABLE_LATCH
#define ENABLE_ARM
//#define ENABLE_CLAW
//#define ENABLE_MACRO_BUTTONS



void armMove(int moveUp);

//Refine presets
void armMacro(int set, int sensor);
const int presets[4] = {0, 360,  720, 1080};

#define NORMAL_SCALE 1.0
#define SLOW_SCALE 0.5
float scale = NORMAL_SCALE;

task main() {
    int encoder = 0;
    while(true) {
        getJoystickSettings(joystick);
        int preset = 0;

        if(joy1Btn(1)) {
        	writeDebugStreamLine("preset set to 1");
            preset = 1;
        }
        if(joy1Btn(2)) {
            preset = 2;
            writeDebugStreamLine("preset set to 2");
        }
        if(joy1Btn(3)) {
            preset = 3;
            writeDebugStreamLine("preset set to 3");
        }
        if(joy1Btn(4)) {
            preset = 4;
            writeDebugStreamLine("preset set to 4");
        }


        if(joy1Btn(7) && joy1Btn(5)) {
            //if both 7 and 5 are depressed DO NOTHING!
            preset = -1;
            armMove(0);
            writeDebugStreamLine("Both #5 and #7 depressed");
        } else if(joy1Btn(7)) {
		//Call are movement function; move down
            armMove(-1);
            preset = -1;
            writeDebugStreamLine("joy1_btn 7 depressed; moving arm down");
        } else if(joy1Btn(5)) {
            //call arm movement function; Move up
            armMove(1);
            preset = -1;
            writeDebugStreamLine("joy1_btn 5 depressed; moving arm up");
	} else if(preset < 0) {
	    armMove(0);
	}


        // NOTE: If the arm motor can turn more than 32,767 degrees in
        //       either direction, the encoder value cannot be relied upon
        //       alone, and a separate variable (preferably a long) should
        //       be used to accumulate encoder ticks.
        if(preset >= 0) {
            armMacro(presets[preset], nMotorEncoder[motorA]);
        } else {

        }
	}
}


void armMove(int moveUp) {
    //TODO: Tune movement speed
#define ARM_SPEED 40
    //TODO: Motor designation changed
    if(moveUp>0) {
        motor[motorA] = ARM_SPEED;
    } else if(moveUp < 0) {
        motor[motorA] = - ARM_SPEED;
    } else {
        motor[motorA] = 0;
    }
    }

    void armMacro(int set, int sensor) {
		#define KP 1
		#define MIN_ERR 15
		#define ARM_SPEEDLIMIT 50
    int err = set - sensor;
    if(abs(err) <= MIN_ERR) {
        motor[motorA] = KP * err;
    	} else {
      	  motor[motorA] = 0;
    	}
		}
