#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
nMotorEncoder[motorA] = 0;
nMotorEncoder[motorB] = 0;
nMotorEncoder[motorC] = 0;
nMotorEncoder[motorD] = 0;
nMotorEncoder[motorE] = 0;
nMotorEncoder[motorF] = 0;
nMotorEncoder[motorG] = 0;
nMotorEncoder[motorH] = 0;
nMotorEncoder[motorI] = 0;
while(true){
	if (nNxtButtonPressed == 3){
		nMotorEncoder[motorA] = 0;
		nMotorEncoder[motorB] = 0;
		nMotorEncoder[motorC] = 0;
		nMotorEncoder[motorD] = 0;
		nMotorEncoder[motorE] = 0;
		nMotorEncoder[motorF] = 0;
		nMotorEncoder[motorG] = 0;
		nMotorEncoder[motorH] = 0;
		nMotorEncoder[motorI] = 0;
	}
	nxtDisplayTextLine(1,"EncoderA: %d", nMotorEncoder[motorA]);
	nxtDisplayTextLine(2,"EncoderB: %d", nMotorEncoder[motorB]);
	nxtDisplayTextLine(3,"EncoderC: %d", nMotorEncoder[motorC]);
	nxtDisplayTextLine(4,"EncoderD: %d", nMotorEncoder[motorD]);
	nxtDisplayTextLine(5,"EncoderE: %d", nMotorEncoder[motorE]);
	nxtDisplayTextLine(6,"EncoderF: %d", nMotorEncoder[motorF]);
	nxtDisplayTextLine(7,"EncoderG: %d", nMotorEncoder[motorG]);
	nxtDisplayTextLine(8,"EncoderH: %d", nMotorEncoder[motorH]);
	nxtDisplayTextLine(9,"EncoderI: %d", nMotorEncoder[motorI]);
}
	//extra code for testing purposes
	//int x = 0;
	//long encoder = 0;
	//bool inc = true;
	//while (true) {
	//motor[motorA] = 5;
	//encoder += nMotorEncoder[motorA];
	//nMotorEncoder[motorA] = 0;
	//writeDebugStreamLine("%d, %d", x, encoder);
//	if (inc){
//	     if (x >= 99) {
//	          inc = false;
//     } else {
//		x++;
//	}
//	}else if(!inc){
//	     if(x <= 1) {
//	     inc = true;
//	} else {
//	     x--;
//	}
//}
}
