#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
nxtDisplayCenteredTextLine(0, "Hit Center");
nxtDisplayCenteredTextLine(1, "button to");
nxtDisplayCenteredTextLine(2, "Reset.");
wait1Msec(3000);
nMotorEncoder[motorA] = 0;
nMotorEncoder[motorB] = 0;
nMotorEncoder[motorC] = 0;
nMotorEncoder[motorD] = 0;
nMotorEncoder[motorE] = 0;
nMotorEncoder[motorF] = 0;
nMotorEncoder[motorG] = 0;
nMotorEncoder[motorH] = 0;
nMotorEncoder[motorI] = 0;
while(true){
	if (nNxtButtonPressed == 3){
		nMotorEncoder[motorA] = 0;
		nMotorEncoder[motorB] = 0;
		nMotorEncoder[motorC] = 0;
		nMotorEncoder[motorD] = 0;
		nMotorEncoder[motorE] = 0;
		nMotorEncoder[motorF] = 0;
		nMotorEncoder[motorG] = 0;
		nMotorEncoder[motorH] = 0;
		nMotorEncoder[motorI] = 0;
	}
	nxtDisplayTextLine(0,"EncoderA: %d", nMotorEncoder[motorA]);
	nxtDisplayTextLine(1,"EncoderB: %d", nMotorEncoder[motorB]);
	nxtDisplayTextLine(2,"EncoderC: %d", nMotorEncoder[motorC]);
	nxtDisplayTextLine(3,"EncoderD: %d", nMotorEncoder[motorD]);
	nxtDisplayTextLine(4,"EncoderE: %d", nMotorEncoder[motorE]);
	nxtDisplayTextLine(5,"EncoderF: %d", nMotorEncoder[motorF]);
	nxtDisplayTextLine(6,"EncoderG: %d", nMotorEncoder[motorG]);
	nxtDisplayTextLine(7,"EncoderH: %d", nMotorEncoder[motorH]);
	nxtDisplayTextLine(8,"EncoderI: %d", nMotorEncoder[motorI]);
}
	//extra code for testing purposes
	//int x = 0;
	//long encoder = 0;
	//bool inc = true;
	//while (true) {
	//motor[motorA] = 5;
	//encoder += nMotorEncoder[motorA];
	//nMotorEncoder[motorA] = 0;
	//writeDebugStreamLine("%d, %d", x, encoder);
//	if (inc){
//	     if (x >= 99) {
//	          inc = false;
//     } else {
//		x++;
//	}
//	}else if(!inc){
//	     if(x <= 1) {
//	     inc = true;
//	} else {
//	     x--;
//	}
//}
}
