#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	//outputs motor value for arm testing
while(true){
	nxtDisplayCenteredTextLine(nMotorEncoder[motorH]);
}
	//extra code for testing purposes
	//int x = 0;
	//long encoder = 0;
	//bool inc = true;
	//while (true) {
	//motor[motorA] = 5;
	//encoder += nMotorEncoder[motorA];
	//nMotorEncoder[motorA] = 0;
	//writeDebugStreamLine("%d, %d", x, encoder);
//	if (inc){
//	     if (x >= 99) {
//	          inc = false;
//     } else {
//		x++;
//	}
//	}else if(!inc){
//	     if(x <= 1) {
//	     inc = true;
//	} else {
//	     x--;
//	}
//}
}
